packages:
  - WebGal/packages/parser
  - WebGal/packages/webgal
  - WebGAL_Terre/packages/editor-preview-protocol
  - WebGAL_Terre/packages/terre2
  - WebGAL_Terre/packages/origine2
  - apps/*

catalog:
  rimraf: 3.0.2
  typescript: 5.9.3
  vscode-ws-jsonrpc: 3.3.2

catalogs:
  legacy-parser:
    typescript: 4.9.5

overrides:
  "img2ico>jimp": 1.6.0

strictDepBuilds: true

allowBuilds:
  "@nestjs/core": false
  "@parcel/watcher": true
  "@scarf/scarf": false
  electron: true
  electron-winstaller: true
  esbuild: true
